const colors = [
  "Red",
  "Orange",
  "Yellow",
  "Green",
  "Blue",
  "Purple",
  "Pink",
  "Brown",
  "Black",
  "White",
  "Gold",
  "Silver",
  "Coral",
  "Turquoise",
  "Magenta",
  "Cyan",
  "Beige",
  "Lavender",
  "Maroon",
  "Olive",
];
const toolbarOptions = [
  ["bold", "italic", "underline"],
  ["blockquote", "code-block"],
  [{ header: 1 }, { header: 2 }],
  [{ list: "ordered" }, { list: "bullet" }],
  [{ script: "sub" }, { script: "super" }],
  [{ indent: "-1" }, { indent: "+1" }],
  [{ direction: "rtl" }, { align: [] }],
  [{ color: colors }, { background: colors }],
  ["clean"],
];
export { toolbarOptions };
